### ISSUE TITLE
Current RequestGenerator Service Configuration is missing method

### ISSUE THREAD

**Issue by petrica** [zeroem/ZeroemCurlBundle#2]
Hi,

Fatal error: Call to undefined method Zeroem\CurlBundle\Curl\RequestGenerator::applyOptions()

You have configured RequestGenerator to receive some configuration options through applyOptions method which is not implemented in class RequestGenerator.

Thanks,
Petrica

**Comment by zeroem** [comment]
Whoops!  Thanks for catching that.

Resolved with: 578fc3dc8c8d2c77c6cec5a5f1969c689e1ffda1

**Comment by petrica** [comment]
Thanks for the Bundle :)
