### ISSUE TITLE
Bug in setPostFields

### ISSUE THREAD

**Issue by white-bear** [zeroem/ZeroemCurlBundle#6]
Zeroem/CurlBundle/HttpKernel/RemoteHttpKernel.php
method setPostFields (line 159)

First, function $request->getContent(); will always return string
So, compare its result with null is useless, you must check result with empty
Old code:
        $content = $request->getContent();

```
    if (null !== $content) {
        $postfields = $content;
```

New version:
        $content = $request->getContent();

```
    if (! empty($content)) {
        $postfields = $content;
```

Second, call $request->getRequest() fails, because there is no such method. request is public var in $request, and you must access it directly.
Old code:
        } else if (count($request->getRequest()->all()) > 0) {
            $postfields = $request->getRequest()->all();
        }
New code:
        } else if (count($request->request->all()) > 0) {
            $postfields = $request->request->all();
        }

That\s all, thanks =)

**Comment by zeroem** [comment]
Thanks for the reports :)

**Comment by white-bear** [comment]
Thaks you for cool bundle ;)
I'm just happy user =)
