### ISSUE TITLE
Package installation fails with composer

### ISSUE THREAD

**Issue by demerzel3** [zeroem/ZeroemCurlBundle#7]
When trying to install the bundle using composer I get the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for zeroem/curl-bundle dev-master -> satisfiable by zeroem/curl-bundle dev-master.
    - zeroem/curl-bundle dev-master requires symfony/http-foundation 2.0-dev -> no matching package found.
```

I think the problem lies in the version of http-foundation, the right version should be "2.0.x-dev" as in https://packagist.org/packages/symfony/http-foundation

**Comment by zeroem** [comment]
see cfe14348cd0c778a5c55d8bf93d0e55431915a20
