### ISSUE TITLE
Lots of undefined constants in older cURL

### ISSUE THREAD

**Issue by rickard2** [zeroem/ZeroemCurlBundle#9]
I'm using your bundle on a CentOS 5.5 box which uses cURL 7.15.5 which means that a lot of constants in `CurlOptions` will be undefined.

I will submit a PR where the static `$option_value_types` is populated dynamically depending on wether the constant is defined on the particular system. I can see that you've run into problems before with some constants commented out. 

Hope you agree with this decision, otherwise I'm open for suggestions or other solutions.

**Comment by zeroem** [comment]
@rickard2 definitely a more complete and cross platform solution.  I'll see about getting it merged in this weekend.

**Comment by zeroem** [comment]
Pull Request merged in.  Closing.
